### ISSUE TITLE
thread 'main' panicked at 'assertion failed: !self.is_different_host(url)?', src\http.rs:127:9

### ISSUE THREAD

**Issue by brian6932** [2bc4/twitch-hls-client#10]
```rust
06:35:42 [DEBUG] twitch_hls_client: Server changed, preconnecting to next
06:35:42 [DEBUG] rustls::client::hs: No cached session for DnsName("video-edge-691824.jfk04.abs.hls.ttvnw.net")
06:35:42 [DEBUG] rustls::client::hs: Not resuming any session
06:35:42 [DEBUG] rustls::client::hs: Using ciphersuite TLS13_AES_128_GCM_SHA256
06:35:42 [DEBUG] rustls::client::tls13: Not resuming
06:35:42 [DEBUG] rustls::client::tls13: TLS1.3 encrypted extensions: []
06:35:42 [DEBUG] rustls::client::hs: ALPN protocol is None
thread 'main' panicked at 'assertion failed: !self.is_different_host(url)?', src\http.rs:127:9
stack backtrace:
   0:     0x7ff7910a647a - <unknown>
   1:     0x7ff79101beab - <unknown>
   2:     0x7ff791089631 - <unknown>
   3:     0x7ff7910a871b - <unknown>
   4:     0x7ff7910a82f7 - <unknown>
   5:     0x7ff7910a92a9 - <unknown>
   6:     0x7ff7910a8cb4 - <unknown>
   7:     0x7ff7910a8c2f - <unknown>
   8:     0x7ff7910a8c04 - <unknown>
   9:     0x7ff7910e7735 - <unknown>
  10:     0x7ff7910e782c - <unknown>
  11:     0x7ff790fe55fb - <unknown>
  12:     0x7ff790fb8ab6 - <unknown>
  13:     0x7ff790fe6601 - <unknown>
  14:     0x7ff7910e5c0c - <unknown>
  15:     0x7ffe279f117e - BaseThreadInitThunk
  16:     0x7ffe289042db - RtlUserThreadStart
```

**Comment by 2bc4** [comment]
Not sure how that happened. I'm going to remove that code as I don't think the original idea behind it works anyways.
